openapi: 3.0.3
info:
  title: Product API
  description: API for user authentication and product management.
  version: 1.0.0

servers:
  - url: http://localhost:9292

paths:
  /login:
    post:
      summary: Authenticate user
      description: Returns a JWT token if the credentials are valid.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user
                - password
              properties:
                user:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Authentication successful
                  token:
                    type: string
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /register:
    post:
      summary: Register user
      description: Registers a new user in the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user
                - password
              properties:
                user:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User registered successfully
        '400':
          description: Registration error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /products:
    get:
      summary: Retrieve products
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '401':
          description: Unauthorized

    post:
      summary: Create product
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '202':
          description: Product creation scheduled
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product creation scheduled
                  name:
                    type: string
        '400':
          description: Invalid product data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Product:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
